version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(asctime)s.%(msecs)03d | %(filename)s | %(levelname)s ] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: 'logs/app.log'
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  root:
        level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
        handlers: [console, file]
        propagate: no
